### ISSUE TITLE
add About page

### ISSUE THREAD

**Issue by ckingbailey** [ckingbailey/dam#38]
Page or pop up should have info about:
* CA water data hackathon
* dam data set
* link to our development repo
* our names, linked to github or personal website or whatever each person wants

**Comment by ckingbailey** [comment]
This is what I have so far for the About modal. What do you think @dcgull @jesrah ?

![screen shot 2018-10-04 at 6 33 09 pm](https://user-images.githubusercontent.com/20404311/46511536-fffc9300-c803-11e8-8800-78cdcceb69fd.png)

**Comment by dcgull** [comment]
I think you should also mention that we first met at the BIDS Hackathon, and add the picture of us all together.
