### ISSUE TITLE
Definitions dropdown

### ISSUE THREAD

**Issue by ckingbailey** [ckingbailey/dam#43]
@dsconstable wrote us a nice PDF of data definitions. @dcgull wants this turned into a dropdown below the map

TIP: Foundation probably has a ready made dropdown for us. Look it up.

**Comment by ckingbailey** [comment]
I found this https://foundation.zurb.com/sites/docs/responsive-accordion-tabs.html for either collapsible or tabbed views

**Comment by dcgull** [comment]
I need to record the 3 min tour of our site by Monday. How quick can we get this last feature completed?

**Comment by ckingbailey** [comment]
I think I can get it done by tomorrow night

**Comment by ckingbailey** [comment]
@dcgull this is coming along. The color is ugly right now. I'm trying to match @dsconstables colors in the pdf. Not sure how that'll look with our page's color scheme. We'll see.

Feedback is, as always, welcome

![screen shot 2018-10-11 at 3 54 24 pm](https://user-images.githubusercontent.com/20404311/46838439-2d01f600-cd6e-11e8-9bee-cad67e90cc6b.png)

**Comment by ckingbailey** [comment]
ok, I think it looks good. Screen caps in PR #44

**Comment by dcgull** [comment]
Love the functionality! Don't match his colors, though, those weren't meant
for being embedded in our website.
